name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        target: [test-clj, test-cljs]

    steps: 
    - name: Setup CI Environment
      uses: yetanalytics/actions/setup-env@v0.0.4-test

    - name: Run make target $${{ matrix.target }}
      run: make ${{ matrix.target }}
